[showdeerocks]
title = "ShowdeeRocks"
url = "http://showdeerocks.info/article.html"
entrySelector = "//html/body/div[@class='Line']"
titleSelector = "//span[contains(@class, 'Artist') or contains(@class, 'Site') or contains(@class, 'Time')]/text()"
linkSelector = "//span[@class='Link']/a"
waitUntil = "networkidle"
