[showdeerocks]
title = "ShowdeeRocks"
url = "http://showdeerocks.info/article.html"
entrySelector = "//html/body/div[@class='Line']"
titleSelector = "//span[@class='Artist'] | //span[@class='Site'] | //span[@class='Time']"
linkSelector = "//span[@class='Link']/a"
waitUntil = "networkidle"
