[showdeerocks]
title = "ShowdeeRocks"
url = "http://showdeerocks.info/article.html"
entrySelector = "//html/body/div"
titleSelector = "//div[@class='Line']"
linkSelector = "//span[@class='Link']/a"
waitUntil = "networkidle"