[showdeerocks]
title = "ShowdeeRocks"
url = "http://showdeerocks.info"
entrySelector = "div.Line"
titleSelector = "span.Artist"
linkSelector = "span.Link a"
waitUntil = "networkidle"

[showdeerocks_article]
title = "ShowdeeRocks"
url = "http://showdeerocks.info/article.html"
entrySelector = "//html/body/div[@class='Line']"
titleSelector = "//span"
linkSelector = "//span[@class='Link']/a"
waitUntil = "networkidle"

[indistreet]
title = "인디스트릿 ─ 공연 목록"
url = "https://indistreet.com/live"
entrySelector = "div.css-1ccuj2z"
titleSelector = "p[class^='chakra-text css']:nth-child(1)"
linkSelector = "a"
imageSelector = "span img"
waitUntil = "networkidle"
onFail = "stale"
