[showdeerocks]
title = "ShowdeeRocks"
url = "http://showdeerocks.info/article.html"
entrySelector = "//html/body/div[@class='Line']"
titleSelector = "//./child::node()"
linkSelector = "//span[@class='Link']/a"
waitUntil = "networkidle"
