[xindieticket_ticket]
title = "XINDIE ─ TICKET"
url = "https://xindieticket.kr/tickets/"
entrySelector = "xi-card.ng-scope"
titleSelector = "h1 div.ng-binding"
linkSelector = "a.ng-scope"
contentSelector = "div.ng-scope"
imageSelector = "a.ng-scope div:nth-child(1)"
waitUntil = "networkidle"
onFail = "stale"

[moumi]
title = "모우미"
url = "https://moumi-shop.com/category/%EA%B3%B5%EC%97%B0/24/"
entrySelector = "ul.prdList.grid2 li[id^='anchorBoxId']"
titleSelector = "strong.name a span:nth-child(2)"
linkSelector = "strong.name a"
contentSelector = "ul[class='xans-element- xans-product xans-product-listitem spec'] li"
imageSelector = "div.prdImg a img"
waitUntil = "networkidle"

[moumi_inpock]
title = "모우미 ─ 인포크링크"
url = "https://link.inpock.co.kr/moumi"
entrySelector = "div.links a.link-a"
titleSelector = "div.link.gtm-link-click-visitor div.link-meta p.inpock-typography.paragraph-2.titleClass.title"
linkSelector = "*"
imageSelector = "div.image"
waitUntil = "networkidle"

[showdeerocks]
title = "ShowdeeRocks"
url = "http://showdeerocks.info"
entrySelector = "div.Line"
titleSelector = "span.Artist"
linkSelector = "span.Link a"
waitUntil = "networkidle"
onFail = "stale"

[showdeerocks_article]
title = "ShowdeeRocks"
url = "http://showdeerocks.info/article.html"
entrySelector = "//html/body/div[@class='Line']"
titleSelector = "//span"
linkSelector = "//span[@class='Link']/a"
waitUntil = "networkidle"
onFail = "stale"

[indistreet]
title = "인디스트릿 ─ 공연 목록"
url = "https://indistreet.com/live"
entrySelector = "div.css-1ccuj2z"
titleSelector = "p[class^='chakra-text css']:nth-child(1)"
linkSelector = "a"
contentSelector = "div[positoin='relative']"
waitUntil = "networkidle"
onFail = "stale"

[festivallife_festival]
title = "페스티벌 라이프 ─ 국내 페스티벌"
url = "https://festivallife.kr/festival"
entrySelector = "div._post_row.post_row div.list-style-card._card_wrap"
titleSelector = "div.title.title-block"
linkSelector = "a.post_link_wrap._fade_link"
imageSelector = "div.card_wrapper"
waitForSelector = "div._post_row.post_row div.list-style-card._card_wrap"
onFail = "stale"

[festivallife_festival_o]
title = "페스티벌 라이프 ─ 해외 페스티벌"
url = "https://festivallife.kr/festival_o"
entrySelector = "div._post_row.post_row div.list-style-card._card_wrap"
titleSelector = "div.title.title-block"
linkSelector = "a.post_link_wrap._fade_link"
imageSelector = "div.card_wrapper"
waitForSelector = "div._post_row.post_row div.list-style-card._card_wrap"
onFail = "stale"

[festivallife_concert]
title = "페스티벌 라이프 ─ 국내공연"
url = "https://festivallife.kr/concert"
entrySelector = "div._post_row.post_row div.list-style-card._card_wrap"
titleSelector = "div.title.title-block"
linkSelector = "a.post_link_wrap._fade_link"
imageSelector = "div.card_wrapper"
waitForSelector = "div._post_row.post_row div.list-style-card._card_wrap"
onFail = "stale"

[festivallife_concert_k]
title = "페스티벌 라이프 ─ 내한공연"
url = "https://festivallife.kr/concert_k"
entrySelector = "div._post_row.post_row div.list-style-card._card_wrap"
titleSelector = "div.title.title-block"
linkSelector = "a.post_link_wrap._fade_link"
imageSelector = "div.card_wrapper"
waitForSelector = "div._post_row.post_row div.list-style-card._card_wrap"
onFail = "stale"
